### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by keoir** [chrismin13/CPCameraStudioReborn#1]
I am having an issue with the API part, I am passing the following. When to calls this it puts the player to the first point looking directly up and does not move.

The command based system works fine, and no errors are being thrown at the init of the call.

CameraStudio.travel(this.player, this.points, CameraStudio.parseTimeString("5m"), null, null);

Please advise.

- Zack

**Comment by chrismin13** [comment]
Could you please show me all the code and tell me what Spigot Version you are using? 
Thanks and sorry for the late reply.
