### ISSUE TITLE
Getting kicked for 'No flying allowed'

### ISSUE THREAD

**Issue by messageofdeath** [chrismin13/CPCameraStudioReborn#2]
This happens when your going through your route sometimes, not everytime, but sometimes.
I found that if you delay the first TP by 1 server tick, this is fixed.
https://github.com/chrismin13/CPCameraStudioReborn/blob/master/src/eu/crushedpixel/camerastudio/CameraStudio.java#L152
Changed that line from '});' to '}, 1L);'
Ever since I edited that part it's never kicked me. Guess it allows more time for the server to process the AllowFlight command.
Don't know if this is an issue, but you allow flight and Flying true, but when it ends you don't set it back to false, or save that info to set it back.

**Comment by chrismin13** [comment]
Thank you for letting me know! I will go ahead and make those changes. :) Next time, you can also submit a pull request, so I can implement the changes immediately. I don't use the plugin almost at all so I wouldn't know if a small bug such as this one was occurring. 
If you ever have any other issues, please, let me know by making another issue here.

**Comment by chrismin13** [comment]
Issue closed! Update has been released.
